# Generated by Django 3.0.7 on 2020-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_ideas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ideas',
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
