# Generated by Django 3.0.7 on 2020-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
