# Generated by Django 3.0.7 on 2020-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200705_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ideas',
            field=models.ManyToManyField(to='app.Idea'),
        ),
    ]
