# Generated by Django 3.0.7 on 2020-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200721_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='icons8-idea-512.png', upload_to=''),
        ),
    ]
