# Generated by Django 3.0.7 on 2020-07-21 16:04

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200721_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
