# Generated by Django 3.0.7 on 2020-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200721_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='image',
        ),
    ]
